// Service layer — re-exports mock data.
// To swap to real API: replace each export with an API call in its respective service file.
// Components import from '@/lib/services' instead of '@/lib/data'.
// Only the files in this directory change when moving to production APIs.

export {
  ACCENT, ACCENT_HOVER, AMBER, ORANGE, GRAY, HEADING,
  CHART_1, CHART_2, CHART_3, CHART_4, CHART_5, tooltipStyle,
  KPI_DATA, DAILY_LEAD_VOLUME, SOURCE_MIX, FUNNEL_DATA,
  CHANNEL_TABLE, CHANNEL_BAR_DATA, ROI_BAR_DATA,
  REVENUE_SERVICES, REVENUE_TREND,
  ALL_LEADS, PIPELINE_LEADS, TEAM_DATA,
  SEO_METRICS, SEO_ISSUES, ALERTS_DATA, AUTO_TOOLS,
  GOALS_DATA, SLA_RULES, SLA_BREACHES_LIVE, SLA_ESCALATIONS,
  BUDGET_CHANNELS, DAILY_SPEND_TREND,
  WA_CONVERSATIONS, WA_TEMPLATES, WA_MESSAGES,
  CALENDAR_ITEMS, COHORT_DATA,
  COMPETITORS, KEYWORD_OVERLAP, COMPETITOR_ACTIVITY, SHARED_KEYWORDS_DATA,
  ASSIGNMENT_RULES, ATTRIBUTION_JOURNEYS,
  RIYA_URGENT_INQUIRIES, RIYA_PULSE_STATS, RIYA_SERVICE_MIX, RIYA_WEEKLY_TARGETS,
  RIYA_PERFORMANCE_SCORECARD, RIYA_SERVICE_BREAKDOWN, RIYA_RESPONSE_TREND,
  RIYA_NOTIFICATIONS, SERVICE_INTELLIGENCE, RIYA_ACTIVITY_MOCK,
  RIYA_DAILY_TASKS, RIYA_SHIFT_GOALS, RIYA_ADMIN_CORRELATION,
  RIYA_PIPELINE_VELOCITY, RIYA_SOURCE_EFFECTIVENESS, RIYA_REVENUE_CORRELATION, RIYA_FUNNEL,
  sourcePillClass, statusPillClass, initials,
} from '@/lib/data'
